name: bump
on: workflow_dispatch
permissions:
  contents: write
  pull-requests: write
env:
  GH_TOKEN: ${{ github.token }}
jobs:
  bump-pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
      with:
        extra-conf: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          extra-substituters = https://tek.cachix.org
          extra-trusted-public-keys = tek.cachix.org-1:+sdc73WFq8aEKnrVv5j/kuhmnW2hQJuqdPJF5SnaCBk=
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - id: bump
      run: |
        nix run .#bump.github-pr
    - name: pr
      id: cpr
      if: steps.bump.outputs.commit-message
      uses: peter-evans/create-pull-request@v5
      with: ${{ steps.bump.outputs }}
