name: test
on: workflow_dispatch
# on:
#   push:
#     branches: [main]
permissions:
  contents: write
  pull-requests: write
env:
  GH_TOKEN: ${{ github.token }}
jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - id: main
      run: |
        stamp=$(date '+%s')
        branch="hix/bump-$stamp"
        echo data > $stamp
        echo "branch=$branch" >> $GITHUB_OUTPUT
        ./write-params.bash
    - name: pr
      id: cpr
      if: steps.main.outputs.modified == true
      uses: peter-evans/create-pull-request@v5
      with: ${{ steps.main.outputs }}
